### ISSUE TITLE
在vivo y23l上完全无法解析安装包

### ISSUE THREAD

**Issue by EL-File4138** [Soptq/Paste#5]
如题，安装包来自酷安，kingroot安装无法解析，转到系统安装仍然无法解析

**Comment by Soptq** [comment]
@EL-File4138 您的系统版本？

**Comment by EL-File4138** [comment]
昨天晚上已找到问题，y23l的系统更新版本停止在1.14，1.14基于Android4.4。
PS：为什么没有可用于4.x的版本呢

**Comment by Soptq** [comment]
@EL-File4138 

因为谷歌从5.0开始启用的材料设计和支持库可以大幅降低开发者的ui代码。而且5.0抛弃了大量以前的API，可以说是安卓的一个分水岭。

4.4会考虑支持的，但是支持意味着需要重写UI和逻辑，所以对4.4的支持不会来的太快。

感谢反馈
