### ISSUE TITLE
软件以后还会继续开发吗？

### ISSUE THREAD

**Issue by Edfgdz** [Soptq/Paste#8]
RT

**Comment by Soptq** [comment]
会，暂时冷冻。现在决定先努力提升自己写程序的水平。谢谢关注，不会弃坑的

**Comment by Edfgdz** [comment]
谷歌键盘已经有了剪贴板功能，但我感觉这个app的剪贴板功能更多，比gboard自带的要好，所以希望这个项目以后还能重启
